image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - cd Source/EasyGelf.NLog
    - dotnet pack -c Release -p:PackageVersion=1.0.0 -p:PackageProjectUrl="$CI_PROJECT_URL"
    - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget push "bin/Release/*.nupkg" --source gitlab

    - cd ../EasyGelf.NLog
    - dotnet pack -c Release -p:PackageVersion=$CI_COMMIT_TAG -p:PackageProjectUrl="$CI_PROJECT_URL"
    - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget push "bin/Release/*.nupkg" --source gitlab
  only:
    - tags
